23 add flow per surface area
Open-Systems-Pharmacology/OSPSuite.Dimensions pull request #24
Opened 2021-12-01 22:28 UTC by msevestre

2021-12-01 22:29 UTC, msevestre commented on OSPSuite.Dimensions.xml
> +        <Unit name="g/kg" factor="1E-3" />
@Yuri05 number #22

2021-12-01 22:29 UTC, msevestre commented on OSPSuite.Dimensions.xml
> +        <Unit name="l/min/1.73m²" factor="1.73 * 1E-2" />
@Yuri05 This is the unit required for InputGFR.... I think this is right..but I suck at units

2021-12-01 22:53 UTC, msevestre commented on OSPSuite.Dimensions.xml
> +        <Unit name="l/min/1.73m²" factor="1.73 * 1E-2" />
I am wondering if `l/min/1.73m²` should be or base unit
OR we need to always convert to this unit in the Class implementation so that we can understand what's going on (the CKD are defined based on different values in this unit)

2021-12-02 09:13 UTC, Yuri05 commented on OSPSuite.Dimensions.xml
> +     <Dimension name="Flow per surface area" baseUnit="l/min/dm²" defaultUnit="l/min/1.73m²">
let's rename the dimension to "Flow per **body** surface area"

2021-12-02 09:16 UTC, Yuri05 commented on OSPSuite.Dimensions.xml
> +        <Unit name="l/min/1.73m²" factor="1.73 * 1E-2" />
Conversion factor must be `1.73*1E+2`

2021-12-02 09:20 UTC, Yuri05 commented on OSPSuite.Dimensions.xml
> +        <Unit name="l/min/1.73m²" factor="1.73 * 1E-2" />
>I am wondering if l/min/1.73m² should be or base unit 

I would keep it "l/min/dm²" to be consistent. Same as for other freaky "per part of the body" units, e.g.
`<Dimension name="Flow per weight organ" baseUnit="l/min/kg organ" defaultUnit="ml/min/100g organ">`

2021-12-02 09:21 UTC, Yuri05 requested changes
s. comments

2021-12-02 13:26 UTC, msevestre commented on OSPSuite.Dimensions.xml
> +        <Unit name="l/min/1.73m²" factor="1.73 * 1E-2" />
That's the factor to go from unit to base unit
So shouldn't it be in fact
1e-2 /1.73 ? 

asking for a friend..

2021-12-02 16:36 UTC, Yuri05 commented on OSPSuite.Dimensions.xml
> +        <Unit name="l/min/1.73m²" factor="1.73 * 1E-2" />
you are right, from "l/min/1.73m²" to "l/min/dm²" should be 1e-2/1.73 :)

2021-12-02 17:05 UTC, msevestre commented on OSPSuite.Dimensions.xml
> +        <Unit name="l/min/1.73m²" factor="1.73 * 1E-2" />
done

2021-12-02 17:06 UTC, msevestre commented
all done. Merging

2021-12-02 17:06 UTC, merged